### ISSUE TITLE
.pocket does not exist

### ISSUE THREAD

**Issue by PatPeter** [RogerFK/stalky106#4]
Since the repository has not been pushed to in 2 months and it is not specified in the README, I am unsure how to warp to the pocket dimension as 106. Is the command .pocket?

**Comment by RogerFK** [comment]
This command no longer exists.

I never updated this command for EXILED, I might give it a try at some point since it's as simple as it can be, but I just don't play this game anymore nor get anything from doing stuff for it. Might re-open this issue or mark it as solved if I ever come back to it.
